### ISSUE TITLE
Typo: replace "bean" with "beam"

### ISSUE THREAD

**Issue by JofArnold** [STMicroelectronics/BlueSTSDK_iOS#2]
E.g. https://github.com/STMicroelectronics-CentralLabs/BlueSTSDK_iOS/blob/866468a01bf96c8f3665cd9cef1a50c949afde63/BlueSTSDK/BlueSTSDK/Features/BlueSTSDKFeatureBeamForming.h#L48

**Comment by GiovanniVisentiniST** [comment]
fix with commit 58421ff14566f41fab54850953c206b6c5b6c3d8
