### ISSUE TITLE
Adding custom feature(UUID problem)

### ISSUE THREAD

**Issue by ANPuroOsso** [STMicroelectronics/BlueSTSDK_iOS#8]
So I'm trying to add a new custom feature to the Android APP. I've already implemented the custom class that extends "Feature", have created the constructor having only the Node as a parameter, and have implemented the ExtractResult extractData method as well as a getter method for extracting data from the sample, as it's instructed in the documentation: https://github.com/STMicroelectronics/BlueSTSDK_Android

As far as step 2 goes, I'm not getting how do I get a "UUID" for this new feature and where exactly I have to add it in my code( the documentation says it has to be done before node connection, but I'm not sure where that would be)

**Comment by GiovanniVisentiniST** [comment]
it is an android related issue
